'use client'

// import { Container, Spinner } from 'react-bootstrap';
import CGTNavbar from '../components/navbar';
// import firebase from "firebase/compat/app";
import SignedOutToast from '../components/SignedOutToast';
import "firebase/compat/auth";
import React, { useState, useContext, useEffect } from "react";
// import app from "../lib/Firebase";
import 'bootstrap/dist/css/bootstrap.min.css';
import '../app/page.module.css';
// import App from 'next/app';
// import { auth } from 'firebaseui';

// #####                       #####  ######  #######                               
// #     # #    #   ##   ##### #     # #     #    #    #    # #####  # #    #  ####  
// #       #    #  #  #    #   #       #     #    #    #    # #    # # ##   # #    # 
// #       ###### #    #   #   #  #### ######     #    #    # #    # # # #  # #      
// #       #    # ######   #   #     # #          #    #    # #####  # #  # # #  ### 
// #     # #    # #    #   #   #     # #          #    #    # #   #  # #   ## #    # 
//  #####  #    # #    #   #    #####  #          #     ####  #    # # #    #  ####  

export default function Home() {
  const [show, setShow] = useState(false);
  const [isLoading, setIsLoading] = useState(true)
  useEffect(() => {
    setTimeout(() => {
      setIsLoading(false);
    }, 750);
  }, []);

  // useEffect(() => {
  //   onAuthStateChanged(auth, (user) => {
  //     if (user) {
  //       // User is signed in, see docs for a list of available properties
  //       // https://firebase.google.com/docs/reference/js/firebase.User
  //       const uid = user.uid;
  //       const displayName = user.displayName;
  //       // ...
  //       console.log("uid", uid)
  //     } else {
  //       // User is signed out
  //       // ...
  //       console.log("user is logged out")
  //     }
  //   });

  // }, [])

  return (
    <div>
      <CGTNavbar />
      <br />
      <SignedOutToast />
      <div className="container">
        <h1>Home Page</h1>
        <p />
        <p>
          Welcome to ChatGPTuring!
        </p>
        <p />
        <p>
          This project was created by Aidan Border, Andrea Morris, and Joshua Rowe for CSC 4899 at Florida Southern College, with advising from Dr. Matthew Eicholtz.
        </p>
        <p />
        <p>
          In this project, we wish to examine a human&apos;s ability to distinguish between human-generated and AI-generated code.</p>
        <p />
        <p>
          We decided to pursue this idea after using ChatGPT, the wildly popular AI chatbot from OpenAI that has the ability to generate human-like responses to prompts and questions, including the generation of code. While there are many positive applications of ChatGPT, one potential negative application that schools are particularly worried about is the possible usage of the software to commit academic dishonesty. In order to combat this issue, many teachers and professors need to determine if a submitted work was generated by a student or by AI.
        </p>
        <p />
        <p>
          With detection of AI content being of such great importance to schools and other institutions, we developed this website to answer two primary questions:
        </p>
        <p />
        <p>
          1. How well can people distinguish between AI-generated and human-generated works?
        </p>
        <p />
        <p>
          2. Are professors more successful at identifying AI-generated works than students?
        </p>
        <p />
        <p>
          We chose to have users analyze code snippets rather than other types of generated content due to the fact that we, as computer science students, have greater access to human-generated code through our coursework than other types of content. Users should evaluate the code not based on functionality, but rather on who you believe the generator to be.
        </p>
        <p />
        <p>
          Thank you for participating in our project!
        </p>
      </div>
    </div>

  )
}

